elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/root-ca.pem"]
#server.ssl.keyPassphrase: 6snZ1P1ERHBj
server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: https://single.sharenj.org
elasticsearch.ssl.verificationMode: none
elasticsearch.username: admin
elasticsearch.password: admin
